// Code generated by mockery v2.23.2. DO NOT EDIT.

package service

import (
	domain "github.com/pklimuk-eng-thesis/data-service/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSensorService is an autogenerated mock type for the SensorService type
type MockSensorService struct {
	mock.Mock
}

type MockSensorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSensorService) EXPECT() *MockSensorService_Expecter {
	return &MockSensorService_Expecter{mock: &_m.Mock}
}

// AddNewRecordToSensorTable provides a mock function with given fields: isEnabled, detected
func (_m *MockSensorService) AddNewRecordToSensorTable(isEnabled bool, detected bool) error {
	ret := _m.Called(isEnabled, detected)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool, bool) error); ok {
		r0 = rf(isEnabled, detected)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSensorService_AddNewRecordToSensorTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNewRecordToSensorTable'
type MockSensorService_AddNewRecordToSensorTable_Call struct {
	*mock.Call
}

// AddNewRecordToSensorTable is a helper method to define mock.On call
//   - isEnabled bool
//   - detected bool
func (_e *MockSensorService_Expecter) AddNewRecordToSensorTable(isEnabled interface{}, detected interface{}) *MockSensorService_AddNewRecordToSensorTable_Call {
	return &MockSensorService_AddNewRecordToSensorTable_Call{Call: _e.mock.On("AddNewRecordToSensorTable", isEnabled, detected)}
}

func (_c *MockSensorService_AddNewRecordToSensorTable_Call) Run(run func(isEnabled bool, detected bool)) *MockSensorService_AddNewRecordToSensorTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool), args[1].(bool))
	})
	return _c
}

func (_c *MockSensorService_AddNewRecordToSensorTable_Call) Return(_a0 error) *MockSensorService_AddNewRecordToSensorTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSensorService_AddNewRecordToSensorTable_Call) RunAndReturn(run func(bool, bool) error) *MockSensorService_AddNewRecordToSensorTable_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSensorRecordsLimitN provides a mock function with given fields: limit
func (_m *MockSensorService) GetLatestSensorRecordsLimitN(limit int) ([]domain.SensorData, error) {
	ret := _m.Called(limit)

	var r0 []domain.SensorData
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.SensorData, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.SensorData); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SensorData)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorService_GetLatestSensorRecordsLimitN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSensorRecordsLimitN'
type MockSensorService_GetLatestSensorRecordsLimitN_Call struct {
	*mock.Call
}

// GetLatestSensorRecordsLimitN is a helper method to define mock.On call
//   - limit int
func (_e *MockSensorService_Expecter) GetLatestSensorRecordsLimitN(limit interface{}) *MockSensorService_GetLatestSensorRecordsLimitN_Call {
	return &MockSensorService_GetLatestSensorRecordsLimitN_Call{Call: _e.mock.On("GetLatestSensorRecordsLimitN", limit)}
}

func (_c *MockSensorService_GetLatestSensorRecordsLimitN_Call) Run(run func(limit int)) *MockSensorService_GetLatestSensorRecordsLimitN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockSensorService_GetLatestSensorRecordsLimitN_Call) Return(_a0 []domain.SensorData, _a1 error) *MockSensorService_GetLatestSensorRecordsLimitN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorService_GetLatestSensorRecordsLimitN_Call) RunAndReturn(run func(int) ([]domain.SensorData, error)) *MockSensorService_GetLatestSensorRecordsLimitN_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockSensorService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSensorService creates a new instance of MockSensorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSensorService(t mockConstructorTestingTNewMockSensorService) *MockSensorService {
	mock := &MockSensorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
